query findMissionByName($name: String!) {
  missions(find: { name: $name }) {
    id
    name
    twitter
    website
    wikipedia
    description
    manufacturers
    payloads {
      id
      nationality
      orbit
      payload_mass_kg
      payload_mass_lbs
      payload_type
      reused
    }
  }
}
